In [1]:
from IPython.display import display
import pandas as pd
import matplotlib.pyplot as plt

carros = pd.DataFrame({'A': [28, 32, 28, 30, 34],

                       'B': [31, 29, 31, 29, 31],

                       'C': [29, 32, 28, 32, 30]})

display(carros)

display(carros.agg(['mean', 'median']))

display(carros.mode())

display(carros.describe())
plt.show()

    A   B   C
0  28  31  29
1  32  29  32
2  28  31  28
3  30  29  32
4  34  31  30

           A     B     C
mean    30.4  30.2  30.2
median  30.0  31.0  30.0

    A   B   C
0  28  31  32

               A          B          C
count   5.000000   5.000000   5.000000
mean   30.400000  30.200000  30.200000
std     2.607681   1.095445   1.788854
min    28.000000  29.000000  28.000000
25%    28.000000  29.000000  29.000000
50%    30.000000  31.000000  30.000000
75%    32.000000  31.000000  32.000000
max    34.000000  31.000000  32.000000